src/ConferenceApp.UI/Controllers/ConferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConferenceApp.UI.Features.Conference;
using Core.CommandProcessorSupport;

namespace ConferenceApp.UI.Controllers
{
    public class ConferenceController : Controller
    {
        private readonly ICommandHandler<IndexQuery, ConferenceIndexViewModel> _indexQueryHandler;
        private readonly ICommandHandler<ConferenceEditViewModel, ConferenceEditViewModel> _addEditHandler;
        private readonly ICommandHandler<AddEditQuery, ConferenceEditViewModel> _addEditQueryHandler;
        private readonly ICommandHandler<BulkEditQuery, ConferenceBulkEditViewModel> _bulkEditQueryHandler;
        private readonly ICommandHandler<ConferenceBulkEditViewModel, ConferenceBulkEditViewModel> _bulkEditHandler;

        public ConferenceController(ICommandHandler<IndexQuery, ConferenceIndexViewModel> indexQueryHandler,
            ICommandHandler<ConferenceEditViewModel, ConferenceEditViewModel> addEditHandler,
            ICommandHandler<AddEditQuery, ConferenceEditViewModel> addEditQueryHandler,
            ICommandHandler<BulkEditQuery, ConferenceBulkEditViewModel> bulkEditQueryHandler,
            ICommandHandler<ConferenceBulkEditViewModel, ConferenceBulkEditViewModel> bulkEditHandler)
        {
            _indexQueryHandler = indexQueryHandler;
            _addEditHandler = addEditHandler;
            _addEditQueryHandler = addEditQueryHandler;
            _bulkEditQueryHandler = bulkEditQueryHandler;
            _bulkEditHandler = bulkEditHandler;
        }

        // GET: Conference
        [HttpGet]
        public ActionResult Index()
        {
            return View(_indexQueryHandler.Handle(new IndexQuery()));
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(new ConferenceEditViewModel());
        }

        [HttpPost]
        public ActionResult Add(ConferenceEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                _addEditHandler.Handle(viewModel);
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            return View(_addEditQueryHandler.Handle(new AddEditQuery { Id = id }));
        }

        [HttpPost]
        public ActionResult Edit(ConferenceEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                _addEditHandler.Handle(viewModel);
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult BulkEdit()
        {
            return View(_bulkEditQueryHandler.Handle(new BulkEditQuery()));
        }

        [HttpPost]
        public ActionResult BulkEdit(ConferenceBulkEditViewModel conferenceBulkEditView)
        {
            if (ModelState.IsValid)
            {
                _bulkEditHandler.Handle(conferenceBulkEditView);
                return RedirectToAction("Index");
            }

            return View(conferenceBulkEditView);
        }
    }
}

src/ConferenceApp.UI/Views/Conference/Add.cshtml
@model ConferenceApp.UI.Features.Conference.ConferenceEditViewModel

@{
    ViewBag.Title = "Add Conference";
}

@using (Html.BeginForm("Add", "Conference", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <h4>Add New Conference</h4>
    <hr />

    <div class="form-group">
        @Html.LabelFor(m => m.ConferenceName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ConferenceName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ConferenceName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HashTag, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HashTag, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.HashTag, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.StartDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.StartDate)
            @Html.ValidationMessageFor(m => m.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.EndDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.EndDate)
            @Html.ValidationMessageFor(m => m.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Cost, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Cost, "Currency")
            @Html.ValidationMessageFor(m => m.Cost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/ConferenceApp.UI/Views/Conference/BulkEdit.cshtml
@model ConferenceApp.UI.Features.Conference.ConferenceBulkEditViewModel

@{
    ViewBag.Title = "Bulk Edit";
}

<h2>Bulk Edit</h2>

<p>
    @Html.ActionLink("Add New Conference", "Add")
</p>

@using (Html.BeginForm("BulkEdit", "Conference", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <th>
                Hash Tag
            </th>
            <th>
                Start Date
            </th>
            <th>
                End Date
            </th>
            <th>
                Cost
            </th>
            <th>
                Attendees
            </th>
            <th></th>
        </tr>

        @for (int i = 0; i < Model.Details.Count; i++)
        {
            <tr>
                    @Html.HiddenFor(x => x.Details[i].Id)
                <td>
                    @Html.TextBoxFor(x => x.Details[i].ConferenceName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Details[i].ConferenceName, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.DisplayFor(x => x.Details[i].HashTag, new { @class = "form-control-static" })
                    @Html.HiddenFor(x => x.Details[i].HashTag)
                </td>
                <td>
                    @Html.EditorFor(x => x.Details[i].StartDate)
                    @Html.ValidationMessageFor(x => x.Details[i].StartDate, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.EditorFor(x => x.Details[i].EndDate)
                    @Html.ValidationMessageFor(x => x.Details[i].EndDate, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.EditorFor(x => x.Details[i].Cost, "Currency")
                    @Html.ValidationMessageFor(x => x.Details[i].Cost, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.DisplayFor(x => x.Details[i].AttendeeCount, new { @class = "form-control-static" })
                </td>
            </tr>
        }

    </table>

    <p>
        <input type="submit" value="Save" class="btn btn-default" />
    </p>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/conference")
}

src/ConferenceApp.UI/Views/Conference/Edit.cshtml
@model ConferenceApp.UI.Features.Conference.ConferenceEditViewModel

@{
    ViewBag.Title = "Edit Conference";
}

<div class="container">
    <h2>Edit</h2>

    @using (Html.BeginForm("Edit", "Conference", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <h4>Edit Conference</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(m => m.ConferenceName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.ConferenceName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ConferenceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.HashTag, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.HiddenFor(m => m.HashTag)
                @Html.DisplayFor(m => m.HashTag, new { @class = "form-control-static" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.StartDate, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.StartDate)
                @Html.ValidationMessageFor(m => m.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.EndDate, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.EndDate)
                @Html.ValidationMessageFor(m => m.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Cost, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Cost, "Currency")
                @Html.ValidationMessageFor(m => m.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/ConferenceApp.UI/Views/Conference/Index.cshtml
@model ConferenceApp.UI.Features.Conference.ConferenceIndexViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Add New Conference", "Add")
</p>
<p>
    @Html.ActionLink("Bulk Edit", "BulkEdit")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Hash Tag
        </th>
        <th>
            Start Date
        </th>
        <th>
            End Date
        </th>
        <th>
            Cost
        </th>
        <th>
            Attendees
        </th>
        <th></th>
    </tr>

    @for (int i = 0; i < Model.Details.Count; i++)
    {
        <tr>
            <td>
                @Html.DisplayFor(x => x.Details[i].ConferenceName)
            </td>
            <td>
                @Html.DisplayFor(x => x.Details[i].HashTag)
            </td>
            <td>
                @Html.DisplayFor(x => x.Details[i].StartDate)
            </td>
            <td>
                @Html.DisplayFor(x => x.Details[i].EndDate)
            </td>
            <td>
                @Html.DisplayFor(x => x.Details[i].Cost)
            </td>
            <td>
                @Html.DisplayFor(x => x.Details[i].AttendeeCount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Details[i].Id })
            </td>
        </tr>
    }

</table>